# Generated by Django 2.0.5 on 2018-07-22 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('pcost', models.IntegerField()),
                ('pcolor', models.CharField(default='black', max_length=20)),
                ('pmfd', models.DateField(default=datetime.datetime(2018, 7, 21, 21, 56, 32, 288195))),
                ('pexfd', models.DateTimeField(default=datetime.datetime(2020, 7, 20, 21, 56, 32, 288195))),
            ],
        ),
    ]
