# Generated by Django 2.0.5 on 2018-07-22 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pexfd',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 23, 46, 17, 236550)),
        ),
        migrations.AlterField(
            model_name='product',
            name='pmfd',
            field=models.DateField(default=datetime.datetime(2018, 7, 21, 23, 46, 17, 236550)),
        ),
    ]
